"""
ChatOps-EC2-Processor  —  SELF-CONTAINED BUILD

Generated by build_standalone.py. Do not edit directly; edit
chatops_common.py or ChatOps-EC2-Processor.py and rebuild.

Paste this whole file into the Lambda console as lambda_function.py.
No layer and no zip required.
"""


import base64
import json
import os
import random
import time
import urllib.error
import urllib.parse
import urllib.request

from botocore.config import Config
import boto3


# --------------------------------------------------------------------------
# Shared helpers (inlined from chatops_common.py)
# --------------------------------------------------------------------------

HTTP_TIMEOUT = 10
GITHUB_API = "https://api.github.com"

_boto_cfg = Config(retries={"max_attempts": 5, "mode": "standard"})
_ddb = boto3.client("dynamodb", config=_boto_cfg)
_secrets = boto3.client("secretsmanager", config=_boto_cfg)

_token_cache = None


class GitHubConflict(Exception):
    """Retryable: branch head moved or the ref is locked."""


class GitHubError(Exception):
    """Non-retryable GitHub failure."""


# ------------------------------------------------------------------ credentials

def github_token():
    """Fetched once per cold start and cached in module scope."""
    global _token_cache
    if _token_cache:
        return _token_cache

    secret_id = os.environ.get("GITHUB_TOKEN_SECRET_ID")
    if secret_id:
        raw = _secrets.get_secret_value(SecretId=secret_id)["SecretString"]
        try:
            _token_cache = json.loads(raw)["token"]
        except (json.JSONDecodeError, KeyError, TypeError):
            _token_cache = raw.strip()
    else:
        # Transitional only. Remove once the secret is in place.
        _token_cache = os.environ["GITHUB_TOKEN"]
    return _token_cache


def _headers():
    return {
        "Authorization": f"Bearer {github_token()}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
        "User-Agent": "jade-chatops/1.0",
    }


# ------------------------------------------------------------------ sequencing

def next_sequence(project, env):
    """
    Atomic monotonic counter per project+env.

    ADD on a missing attribute initialises to 0 then adds, so the first call
    returns 1. Single round trip, no read-modify-write race.
    """
    resp = _ddb.update_item(
        TableName=os.environ["COUNTER_TABLE"],
        Key={"counter_key": {"S": f"{project}#{env}"}},
        UpdateExpression="ADD seq :one",
        ExpressionAttributeValues={":one": {"N": "1"}},
        ReturnValues="UPDATED_NEW",
    )
    return int(resp["Attributes"]["seq"]["N"])


# ------------------------------------------------------------------ HCL writing

def hcl_assignments(pairs, width=16):
    """
    Render tfvars lines with injection-safe values.

    json.dumps produces a JSON string literal, which is also a valid HCL string
    literal, and correctly escapes quotes, backslashes and newlines. The original
    f-string approach let a value containing a quote inject arbitrary HCL into a
    file the pipeline then executes with its own IAM role.
    """
    lines = []
    for key, value in pairs:
        if isinstance(value, bool):
            rendered = "true" if value else "false"
        elif isinstance(value, (int, float)):
            rendered = str(value)
        else:
            rendered = json.dumps(str(value))
        lines.append(f"{key.ljust(width)} = {rendered}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ GitHub calls

def _request(url, method, payload=None):
    data = json.dumps(payload).encode("utf-8") if payload is not None else None
    req = urllib.request.Request(url, data=data, headers=_headers(), method=method)
    try:
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT) as res:
            raw = res.read().decode()
            return res.getcode(), (json.loads(raw) if raw else {})
    except urllib.error.HTTPError as exc:
        detail = ""
        try:
            detail = exc.read().decode()[:500]
        except Exception:
            pass
        if exc.code in (409, 422):
            raise GitHubConflict(f"{exc.code} on {method} {url}: {detail}")
        if exc.code == 404:
            return 404, {}
        raise GitHubError(f"{exc.code} on {method} {url}: {detail}")
    except urllib.error.URLError as exc:
        # Network-level: worth retrying, so surface as conflict-class.
        raise GitHubConflict(f"network error on {method} {url}: {exc.reason}")


def get_sha(repo, path, branch):
    """Return the blob sha, or None if the file does not exist."""
    url = f"{GITHUB_API}/repos/{repo}/contents/{path}?ref={urllib.parse.quote(branch)}"
    code, body = _request(url, "GET")
    if code == 404:
        return None
    return body.get("sha")


def commit_file(repo, path, content, message, branch, attempts=5):
    """
    Create or update a file, retrying conflicts.

    The sha is re-read on every attempt. Reusing a stale sha after a 409 just
    produces another 409 — that is why the original code could not be fixed by
    wrapping it in a naive retry.
    """
    url = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    for attempt in range(attempts):
        sha = get_sha(repo, path, branch)
        payload = {
            "message": message,
            "content": _b64(content),
            "branch": branch,
        }
        if sha:
            payload["sha"] = sha
        try:
            _, body = _request(url, "PUT", payload)
            return body.get("commit", {}).get("sha")
        except GitHubConflict:
            if attempt == attempts - 1:
                raise
            _backoff(attempt)


def delete_file(repo, path, message, branch, attempts=5):
    """Delete a file. Returns False if it was already absent."""
    url = f"{GITHUB_API}/repos/{repo}/contents/{path}"
    for attempt in range(attempts):
        sha = get_sha(repo, path, branch)
        if sha is None:
            return False
        try:
            _request(url, "DELETE", {"message": message, "sha": sha, "branch": branch})
            return True
        except GitHubConflict:
            if attempt == attempts - 1:
                raise
            _backoff(attempt)


def move_file(repo, src, dst, message, branch):
    """
    Copy then delete — used for the destroy flow, where the manifest must survive
    so `terraform destroy -var-file` still has its inputs.
    """
    url = f"{GITHUB_API}/repos/{repo}/contents/{urllib.parse.quote(src)}?ref={urllib.parse.quote(branch)}"
    code, body = _request(url, "GET")
    if code == 404:
        return False
    content = base64.b64decode(body["content"]).decode()
    commit_file(repo, dst, content, message, branch)
    delete_file(repo, src, message, branch)
    return True


def _b64(text):
    return base64.b64encode(text.encode()).decode()


def _backoff(attempt):
    time.sleep((2 ** attempt) * 0.5 + random.random())


# --------------------------------------------------------------------------
# Handler
# --------------------------------------------------------------------------

REQUIRED = ("project", "env", "requester_name", "instance_type", "os_name", "request_id")


def lambda_handler(event, context):
    inputs = event.get("parsedInput") or event

    missing = [k for k in REQUIRED if not inputs.get(k)]
    if missing:
        raise ValueError(f"EC2 processor missing fields: {', '.join(missing)}")

    project = inputs["project"]
    env = inputs["env"]
    owner = inputs["requester_name"]
    instance_type = inputs["instance_type"]
    os_name = inputs["os_name"]
    request_id = inputs["request_id"]

    # Atomic and monotonic. Concurrent invocations get distinct numbers.
    seq = next_sequence(project, env)
    name = f"{project}-{env}-{seq}"

    tfvars = hcl_assignments([
        ("instance_name", name),
        ("os_name", os_name),
        ("instance_type", instance_type),
        ("project_code", project),
        ("project_owner", owner),
        ("request_id", request_id),
        ("root_volume_size", int(os.environ.get("DEFAULT_VOLUME_SIZE", "20"))),
    ])

    repo = os.environ["REPO_NAME"]
    branch = os.environ.get("BRANCH", "main")
    path = f"environments/{env}/ec2/config/{name}.tfvars"

    commit_sha = commit_file(
        repo=repo,
        path=path,
        content=tfvars,
        message=f"ChatOps [EC2]: provision {name} (ticket {request_id})",
        branch=branch,
    )

    return {
        "name": name,
        "resource_type": "ec2",
        "request_id": request_id,
        "manifest_path": path,
        # One state file per resource. Without this every apply shares a single
        # resource address and each new request destroys the previous instance.
        "backend_key": f"environments/{env}/ec2/{name}/terraform.tfstate",
        "commit_sha": commit_sha,
    }
